use crate::error::CiteError;
use crate::manifest::Manifest;
use std::fs;
use std::path::Path;
use tracing::instrument;

pub struct InitReport {
    pub directories_created: Vec<String>,
    pub files_created: Vec<String>,
    pub files_skipped: Vec<String>,
}

#[instrument(skip(root), fields(project = %name))]
pub fn init_project(name: &str, root: &Path) -> Result<InitReport, CiteError> {
    let mut report = InitReport {
        directories_created: vec![],
        files_created: vec![],
        files_skipped: vec![],
    };

    if !root.exists() {
        fs::create_dir_all(root)?;
        report
            .directories_created
            .push(root.to_string_lossy().to_string());
    }

    for sub in ["content", "assets/audio", "assets/image"] {
        let path = root.join(sub);
        if !path.exists() {
            fs::create_dir_all(&path)?;
            report.directories_created.push(sub.to_string());
        }
    }

    let manifest_path = root.join("cite.toml");
    if !manifest_path.exists() {
        fs::write(&manifest_path, manifest_template(name)?)?;
        report.files_created.push("cite.toml".to_string());
    } else {
        report
            .files_skipped
            .push("cite.toml (already exists)".to_string());
    }

    let meta_path = root.join("metadata.yml");
    if !meta_path.exists() {
        fs::write(&meta_path, metadata_template())?;
        report.files_created.push("metadata.yml".to_string());
    } else {
        report
            .files_skipped
            .push("metadata.yml (already exists)".to_string());
    }

    let gitignore_path = root.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(&gitignore_path, "build/\n.cite-cache.json\n")?;
        report.files_created.push(".gitignore".to_string());
    } else {
        report
            .files_skipped
            .push(".gitignore (already exists)".to_string());
    }

    Ok(report)
}

fn manifest_template(name: &str) -> Result<String, CiteError> {
    let manifest = Manifest::default_template(name);
    let enabled_extensions = manifest
        .compiler
        .enabled_extensions
        .iter()
        .map(|ext| format!("\"{ext}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let audio_formats = manifest
        .assets
        .audio_formats
        .iter()
        .map(|ext| format!("\"{ext}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let image_formats = manifest
        .assets
        .image_formats
        .iter()
        .map(|ext| format!("\"{ext}\""))
        .collect::<Vec<_>>()
        .join(", ");

    Ok(format!(
        r#"# cite-cli project manifest
# Generated by `cite-cli init`. Edit the values below to configure your project.

# Project identity
# name: Display name of the project.
# language: Language code for generated content (e.g. "en").
# metadata_file: Path to the content metadata file, relative to the project root.
# artist_id: Artist UUID from the database (provided by Aoux team).

[project]
name = "{name}"
language = "{language}"
metadata_file = "{metadata_file}"
artist_id = "{artist_id}"

# Build Configuration
# compiler_version: Compiler protocol version this project targets.
# incremental: Rebuild only when inputs change (true = incremental builds).
# output_format: Output format of the build artifact ("json").

[build]
compiler_version = {compiler_version}
incremental = {incremental}
output_format = "{output_format}"

# Deployment (optional — Needed for staging podcasts to Aoux Server, uncomment to enable)
# staging_url: URL of the Aoux Server to deploy to.
# staging_service_key: Supabase anon/publishable key (client key). For user-scoped deploys, run 'cite-cli login' or use a service-role secret here (Ask Aoux team).

# [backend]
# staging_url = ""
# staging_service_key = ""

# Compiler, Assets, Validation
# enabled_extensions: Compiler extensions enabled for this project.
# audio_formats: Allowed audio asset extensions.
# image_formats: Allowed image asset extensions.
# strict: Enable strict validation rules (true = fail on warnings).

[compiler]
enabled_extensions = [{enabled_extensions}]

[assets]
audio_formats = [{audio_formats}]
image_formats = [{image_formats}]

[validation]
strict = {strict}
"#,
        name = manifest.project.name,
        language = manifest.project.language,
        metadata_file = manifest.project.metadata_file,
        artist_id = manifest.project.artist_id,
        compiler_version = manifest.build.compiler_version,
        incremental = manifest.build.incremental,
        output_format = manifest.build.output_format,
        enabled_extensions = enabled_extensions,
        audio_formats = audio_formats,
        image_formats = image_formats,
        strict = manifest.validation.strict,
    ))
}

fn metadata_template() -> String {
    r#"# Podcast content metadata for cite-cli
# Each item under `podcasts` becomes one news/podcast entry when built.
# Uncomment the example below (remove the leading `# `) to define your first podcast.

podcasts:
  # - title: "My First Podcast" # Display title of the episode
  #   file: content/episode.md  # Markdown source for the episode content
  #   source_url: ""            # Original URL (records the reference domain); optional
  #   category: ""              # Category name; created in the DB if missing; optional
  #   thumbnail: ""             # Path under assets/image; optional
  #   audio: ""                 # Path under assets/audio; optional
  #   citation: ""              # BibTeX file; timelines are generated from its entries; optional
"#
    .to_string()
}
