use crate::manifest::Manifest;
use crate::metadata::Metadata;
use crate::report::CiteError;
use std::fs;
use std::path::Path;
use tracing::instrument;

const AUTO_GEN_HEADER: &str = r#"# This file was autogenerated by cite-cli init
# https://github.com/VinayIN/cite-cli
#
# Copyright 2026, Binay Pradhan
# SPDX-License-Identifier: MIT

"#;

pub struct InitReport {
    pub directories_created: Vec<String>,
    pub files_created: Vec<String>,
    pub files_skipped: Vec<String>,
}

#[instrument(skip(root), fields(project = %name))]
pub fn init_project(name: &str, root: &Path) -> Result<InitReport, CiteError> {
    let mut report = InitReport {
        directories_created: vec![],
        files_created: vec![],
        files_skipped: vec![],
    };

    if !root.exists() {
        fs::create_dir_all(root)?;
        report
            .directories_created
            .push(root.to_string_lossy().to_string());
    }

    for sub in ["content", "assets/audio", "assets/image"] {
        let path = root.join(sub);
        if !path.exists() {
            fs::create_dir_all(&path)?;
            report.directories_created.push(sub.to_string());
        }
    }

    let manifest_path = root.join("cite.toml");
    if !manifest_path.exists() {
        fs::write(&manifest_path, manifest_template(name)?)?;
        report.files_created.push("cite.toml".to_string());
    } else {
        report
            .files_skipped
            .push("cite.toml (already exists)".to_string());
    }

    let meta_path = root.join("metadata.yml");
    if !meta_path.exists() {
        fs::write(&meta_path, metadata_template()?)?;
        report.files_created.push("metadata.yml".to_string());
    } else {
        report
            .files_skipped
            .push("metadata.yml (already exists)".to_string());
    }

    let gitignore_path = root.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(
            &gitignore_path,
            format!("{AUTO_GEN_HEADER}\nbuild/\n.cite-cache.json\n"),
        )?;
        report.files_created.push(".gitignore".to_string());
    } else {
        report
            .files_skipped
            .push(".gitignore (already exists)".to_string());
    }

    Ok(report)
}

fn manifest_template(name: &str) -> Result<String, CiteError> {
    let manifest = Manifest::default_template(name);
    let body = toml::to_string(&manifest).map_err(|e| CiteError::Config(e.to_string()))?;
    Ok(format!("{AUTO_GEN_HEADER}\n{body}"))
}

fn metadata_template() -> Result<String, CiteError> {
    let meta = Metadata::default();
    let body = serde_yaml::to_string(&meta)?;
    Ok(format!(
        "{AUTO_GEN_HEADER}# Add your podcast entries below. Each entry becomes one episode.\n\
#   title:     Display title of the episode\n\
#   file:      Path to the Markdown source\n\
#   source_url: Original URL (optional)\n\
#   category:  Category name (optional)\n\
#   thumbnail: Path under assets/image (optional)\n\
#   audio:     Path under assets/audio (optional)\n\
#   citation:  Path to BibTeX file (optional)\n\
{}\n",
        body.trim_end(),
    ))
}
